### ISSUE TITLE
Radio and Checkbox not working

### ISSUE THREAD

**Issue by niklasgrewe** [noahsalvi/svelte-use-form#10]
I tested this REPL: https://svelte.dev/repl/d4fc021f688d4ad0b3ceb9a1c44c9be9?version=3.34.0

the radio buttons are not validated. Even if I don't have any selected (and have filled in all other fields) I can perform the submit function. In my case, I am using a checkbox that I would like to validate. Unfortunately, the `required` validator only works for input fields and not for checkboxes. Would it be possible to add a validator for radio buttons or checkboxes too?

**Comment by noahsalvi** [comment]
This is now supported in `2.2.2`

Checkboxes will have the value "checked" when active and you can can also use validators on radio buttons and checkboxes.

Thank you for reporting 😁
