### ISSUE TITLE
please remove console.log(state) 

### ISSUE THREAD

**Issue by niklasgrewe** [noahsalvi/svelte-use-form#11]
I don't know if you intended it, but I noticed in the Console that the form is constantly output. 
This concerns this code part:

https://github.com/noahsalvi/svelte-use-form/blob/5e9ef020258e4cdb13fff1f2eb183e37c3e6b0de/src/useForm.ts#L107

Could you remove this if it is not needed?

**Comment by noahsalvi** [comment]
Remove in v2.2.1
