### ISSUE TITLE
Reset form

### ISSUE THREAD

**Issue by joshua1** [noahsalvi/svelte-use-form#14]
Hi @noahsalvi , 
Thanks for this library. I wish to ask how the form values can be reset. while it exposes a store, it does not expose a set or update method with which one can reset the store to , e.g an initial state

**Comment by tthsympa** [comment]
Have the same problem here. To reset values I use `bind:this={form}` and later `form.reset()`but it does not reset the state of other values (touched, errors, whatever)

**Comment by noahsalvi** [comment]
Hey guys, sorry for the late response but I wanted to tell you, that this is now added in 2.4.0
`$form.reset()` to reset the whole form.
`$form.email.reset()` to reset for example the email field.
`$form.email.reset({ value: "Set the value it should have after the reset })` You can also set the value manually, if omitted it will have the initial value of the field.
