### ISSUE TITLE
Async validators

### ISSUE THREAD

**Issue by jonathanblancor** [noahsalvi/svelte-use-form#15]
Hello,

Thank you for this awesome project.

I would like to ask if async validators are possible? And if so, how would it be done?

**Comment by noahsalvi** [comment]
Hey Jonathan sorry for the late response.

Yes async validation is possible, I made you a quick example, on how I would implement it. This works as intended on 2.4.1.
https://svelte.dev/repl/d8efbe78251d431184f7429082c74066?version=3

**Comment by jonathanblancor** [comment]
Thanks!
