### ISSUE TITLE
how to do i access the $form with a dynamically name variable

### ISSUE THREAD

**Issue by fabform** [noahsalvi/svelte-use-form#18]
if i have a form with a select that looks like this, where the name property is created at runtime
( I dont know how many controls I need until runtime)

<select name="{something}"  use:validators={[requiredValidator]}>

how do i access the $form property without using HINT, i want to dynamically change the CSS

{#if $form.{something}?.touched }

**Comment by noahsalvi** [comment]
https://svelte.dev/repl/aa5bd9f807284b9783447341fac78919?version=3.41.0
I hope that this example includes the solution to your problem.

Probably what you're searching is this => $form["string or the variable of the name"]?.touched;
