### ISSUE TITLE
does this work with sveltekit ? 

### ISSUE THREAD

**Issue by Lakedaemon** [noahsalvi/svelte-use-form#19]
my sveltekit (which is not hte latest available) is complaining about the usage of "require" instead of import, when I do 

import { useForm, Hint, validators, minLength } from "svelte-use-form";

**Comment by noahsalvi** [comment]
Yes it does work with sveltekit.

Did you install it as a dev dependency?

If not maybe it's due to the older version of sveltekit that you have installed.

**Comment by Lakedaemon** [comment]
Thanks for the reply.
I'll try to update my sveltekit installation.
Have a good day ! :)

**Comment by Lakedaemon** [comment]
I fixed my installation and my npm imports and it works indeed.

I needed to do "npm i" instead of "npm i -D"...to prevent the error I reported (in case this is usefull to someone)

**Comment by noahsalvi** [comment]
> I fixed my installation and my npm imports and it works indeed.
> 
> 
> 
> I needed to do "npm i" instead of "npm i -D"...to prevent the error I reported (in case this is usefull to someone)

interesting, thanks for sharing!

**Comment by aslak01** [comment]
I'm getting an error that persists whether I install as dev dependency or normal dependency. 

`ReferenceError: exports is not defined
    at eval (/node_modules/.pnpm/svelte-use-form@2.4.1/node_modules/svelte-use-form/components/Hint.svelte:15:24) `

**Comment by aslak01** [comment]
Turns out the issue was that I didn't have typescript enabled in my svelte kit project.

**Comment by noahsalvi** [comment]
> Turns out the issue was that I didn't have typescript enabled in my svelte kit project.

Hmm weird, were you on the newest @sveltejs/kit version when you got that error?
Because I just tried creating a sveltekit project without typescript and it seems to work just fine.

**Comment by aslak01** [comment]
Yeah, I got the error when upgrading packages in a ≈ two months old project. I also got it working fine in an empty project with only the actual component I was using. However when importing the rest of my code it for some reason wouldn't work without adding TS.
