### ISSUE TITLE
"500 document is not defined" when using SSR

### ISSUE THREAD

**Issue by LeanderG** [noahsalvi/svelte-use-form#2]
Since version 1.0.2 when rendering on the server I'm getting an error message. I'm guessing it trys to call the chrome specific code on the server.

Here is a reproduction:
https://github.com/LeanderG/svelte-use-form-repro

It's just a SvelteKit app with the example code added to src/routes/index.svelte.

**Comment by noahsalvi** [comment]
This should now be fixed in version 1.0.3,  just make sure to use it as a devDependency
