### ISSUE TITLE
How to handle async data 

### ISSUE THREAD

**Issue by conoroshea1996** [noahsalvi/svelte-use-form#25]
Hey awesome library.
Im wondering if theres a way to handle this as I can't see anything in the demo's sorry if its there.
Im fetching data from an api and populating the fields with that data. 
An issue Im running into is because the data is not set instantly.
It does not update the values in the form making them invalid 
so for example here the name should have the company name value

![Capture](https://user-images.githubusercontent.com/47694309/145251472-4cd51cac-32c4-487a-a575-50dec54ddf3f.PNG)

Is there a way to force an update after fetching from the Api

**Comment by noahsalvi** [comment]
thank you!

no worries, It's probably still missing from the examples
Here are some [suggestions](https://github.com/noahsalvi/svelte-use-form/issues/23#issuecomment-962228642)

**Comment by conoroshea1996** [comment]
Cheers thanks for the response
I'll have have a play around and see if somethings works 
I'll close this issue
