### ISSUE TITLE
chromeAutofill.ts is creating a new style tag for every input in the form

### ISSUE THREAD

**Issue by KyranRana** [noahsalvi/svelte-use-form#29]
Hi I've noticed chromeAutofill.ts is creating a new style tag for every text input in the form, and this is a problem for me because I am creating a new form dynamically based on a select field. In my situation it's causing the plugin to add new style tags whenever I update the select field.

isn't it a bit excessive to add the same autofill style tag for every input? Why not just add it once if it doesn't exist on the page, rather than add it for every single text input. the code doesn't change based on a input field:

```
@keyframes svelte-use-form-webkit-autofill {
    from {}
}

input:-webkit-autofill {
    animation-name: svelte-use-form-webkit-autofill;
}
```

**Comment by noahsalvi** [comment]
Nice idea, thank you :)
