### ISSUE TITLE
Select field validation

### ISSUE THREAD

**Issue by ryanballa** [noahsalvi/svelte-use-form#3]
Is required or custom validation supported for select fields? I tried both and couldn't get a selected option to make the form valid. It seems the custom validation function only ran once on form load instead of whenever the field changed.

**Comment by noahsalvi** [comment]
No, currently not. 
I wasn't sure how likely it would be for people to use selects or textareas with svelte-use-form, but adding that functionality will be pretty straight forward. 
Thanks for pointing that out, I'll work on it

**Comment by ryanballa** [comment]
Awesome! Radios would be a nice addition too. 😀
