### ISSUE TITLE
Undefined formControl in validatorsAction

### ISSUE THREAD

**Issue by dustinc** [noahsalvi/svelte-use-form#31]
I will continue to look into this myself, but wanted to mention it here in case I am doing something blatantly wrong.

I have a form with the ability to add a new group of fields... so a repeatable dataset. The issue is that the validation bindings are not applying to the newly added fields (until saved and page refreshed). 

Please see this REPL for a stripped down implementation, and to reproduce.
https://svelte.dev/repl/b0f3f08700ae451d9ddf0330049a6375?version=3.47.0

To reproduce:
- Click `Add Subform` button - should see new fieldset w/ Leak Detector select field (empty select on purpose... point is to see form validation errors), and should see error message in console.
- Click `Save Form` button - should see validation hint message for all Leak Detector select fields, but the one(s) added w/ `Add Subform` button do not.

If my implementation is incorrect, please advise. Thank you

**Comment by dustinc** [comment]
@noahsalvi The solution I found is to add `subtree: true` to observer.observe options in useForm.ts
<img width="1301" alt="Screen Shot 2022-04-20 at 9 16 58 PM" src="https://user-images.githubusercontent.com/344803/164352394-2367bccc-539b-4806-8090-8bc2981a0d62.png">

I'm happy to create a PR with this solution, or even make the observer options configurable via `useForm()` since maybe not everyone will want to observe descendants.

**Comment by c00** [comment]
I have the same issue. I would love to see this PR merged @noahsalvi

**Comment by noahsalvi** [comment]
Hey @dustinc
Actually, that would be awesome!
I'll write you a mail. :)
