### ISSUE TITLE
Allow `<input>` to be empty if not required.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [noahsalvi/svelte-use-form#35]
I have a situation where I don't `require` the user to input an email-address. However, if the user _does_ input an email-address, I would like that email-address to be validated.

How can I do nothing if there is no email-address, but validate if there is one. I expected the code below to do exactly that ... however, currently the email _always_ is validated, as if it were `required`.

```svelte
<input
    type="email"
    name="adminEmail"
    use:validators={[email, maxLength(250)]}
    placeholder="None"
/>
<HintGroup for="adminEmail">
    <Hint on="email">Email is not valid</Hint>
    <Hint on="maxLength">Email is too long</Hint>
</HintGroup>
```

I'm using **Version `2.4.3`**

**Comment by moalamri** [comment]
Write a validator that returns null if empty and returns ValidationErrors if not empty and not valid.
Here's an example using v8n for pattern validation
```ts
export function email(value: string): null | ValidationErrors {
  const isEmpty = v8n().empty().test(value);
  if(isEmpty) return null;
  const isValidEmail = v8n().pattern(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/).test(value);
  return isValidEmail ? null : { email: 'Invalid email' };
}
```

By default (as the documents says), if you return `null` it will be valid value.
