### ISSUE TITLE
support from Svelte Material UI

### ISSUE THREAD

**Issue by friksa** [noahsalvi/svelte-use-form#37]
Love this project, but not compatible with Material UI.  Are there any plans to support Svelte Material UI?

**Comment by noahsalvi** [comment]
Hey thank you friska

Actually you can partially use it with svelte material ui. The magic of svelte-use-form is that you only need the `name` attribute to be set on the input element and as far as I understand setting it via `input$name` should work. 

The drawback is that can't use the `use:validator` so you'll have to specify the validators in the `useForm` call.
`const form = useForm({ name: { validators: [required, email] } })`
`<Textfield .... input$name="email" />`

Pleas let me know if this works
