### ISSUE TITLE
Feature Request: Provide a way to dynamically update form fields

### ISSUE THREAD

**Issue by Nitecon** [noahsalvi/svelte-use-form#49]
I've been using `svelte-use-form` in my project, and I've encountered a scenario where I need to dynamically update a form field's value. Specifically, I am using the FileReader API to read the contents of a file input and update a textarea with the file's content.

Currently, there doesn't seem to be a straightforward way to update a form field's value programmatically. It would be helpful to have a method or a simple way to update the form field, like:

```js
formData.content = "foo";
$form.update();
```
This would allow developers to update a form field's value programmatically and trigger any necessary validation checks. It would be particularly useful for scenarios where the form's state needs to be updated based on user interactions or external events, like a profile page where the user's data may be loaded after the initial form subscribe where the initial values are not available yet.

Please let me know if there are any workarounds or if this feature is already available but not documented.

Thank you for your consideration!

**Comment by noahsalvi** [comment]
I believe you're looking for `$form.fieldName.change("foo")`
This will change the value in the corresponding html element and also inside the packages internal logic.

**Comment by Nitecon** [comment]
That does not seem to work, here is an example of making use of what you provided:

```
  const form = useForm({
        first_name: {validators: [minLength(2)]},
        last_name: {validators: [minLength(2)]},
        username: {validators: [minLength(3)]},
        email: {validators: [email]},
    })
    let unsubForm = form.subscribe((data) => {
        formData = data;
    });

    let unsubUser = userEvents.subscribe((data) => {
        loggedIn = data.isLoggedIn;
        userData = data.userData;
        let firstName = userData.first_name || "";
        $form.first_name.change(firstName);
    });```

Change as mentioned here is an unresolved function or method. There is also no `$form.fieldName` nor is there an object at $form.first_name as I would expect based on your example.

Thank you!

**Comment by noahsalvi** [comment]
I have created a REPL based on my understanding of your issue, but I have been unable to reproduce the error. 
https://svelte.dev/repl/3550f41cd7024a7883c83146d6d104bb?version=3.58.0

Could it be that you're using svelte-use-form outside of a svelte file and thus the dollar sign prefix isn't recognised?

**Comment by Nitecon** [comment]
I'm not using sveltekit (maybe that has something to do with it?), and using pure svelte for the application, second to this I'm not sure as to why it shows up the way I see it, I seem to be doing the exact same includes:
```
import {email, Hint, minLength, useForm} from "svelte-use-form";
```

The structure of the app has it's entry point under App.svelte as normal which imports a component like this based on functionality but it's all still within the scope of svelte.

Now from my package.json I do run these versions, maybe there is an issue there?
```
"svelte": "^3.55.0",
    "svelte-loader": "github:sveltejs/svelte-loader",
    "svelte-use-form": "^2.0.0",
    ```

Thanks for the help btw, hopefully I'm just the outlier and no one else will ever hit this as it's a really great addon!

**Comment by noahsalvi** [comment]
No worries, I'm always happy to help!

Your import statement and the version you have specified for the package seem alright to me.
Could you please print `$form` and paste the output of it?
