### ISSUE TITLE
Support Svelte 4

### ISSUE THREAD

**Issue by maxime-carbonneau** [noahsalvi/svelte-use-form#52]
Hello,

Update the dependencies to use Svelte 4 please.

**Comment by noahsalvi** [comment]
I've just now noticed that we have svelte as a dependency and not as, what would be wiser, a peer dependency. I have now corrected it. With this change svelte-use-form will no longer be shipped with its own version of svelte but rather use the svelte version provided by its environment - namely the main application. 

Thus `svelte-use-form` can now be used with svelte 3 and svelte 4 and as a bonus its distribution size was reduced.


Thanks Maxime.
