### ISSUE TITLE
500 - Function called outside component initialization

### ISSUE THREAD

**Issue by niklasgrewe** [noahsalvi/svelte-use-form#8]
I am trying to use this library in sveltekit with vitejs. Everthing works fine, but when i restart the dev server, i get this error:

```
500
Function called outside component initialization

Error: Function called outside component initialization
    at get_current_component (/path/to/project/node_modules/.pnpm/svelte-use-form@2.0.1/node_modules/svelte-use-form/dist/index.umd.js:118:19)
```
What could be the reason that I get this error? Can this be solved? I have seen that this error has also already occurred in Sapper. Maybe i should use svelte for my frontend after all 😄 

I use the library in my component like this:
```html
<script>
import { useForm } from 'svelte-use-form'

const form = useForm()
</script>
```
or do i need to wrapp it in a `onMount` function?

**Comment by niklasgrewe** [comment]
i think i found the error. The error directs me to the `Hint.svelte` file. I saw that you are using typescript in the `<script>` tag Currently typescript is not yet supported by Sveltekit. The Preprocessor doesn't work at the moment. Possibly that's why I'm getting this error.

**Comment by noahsalvi** [comment]
Hmm for sapper I know that you get this error message when you use an external component as a `dependency` but for sveltekit I have no idea.
``` bash
500
Function called outside component initialization

Error: Function called outside component initialization
    at get_current_component (/Users/sav/workspace/500/my-app/node_modules/svelte-use-form/node_modules/svelte/internal/index.mjs:649:18)
    at setContext (/Users/sav/workspace/500/my-app/node_modules/svelte-use-form/node_modules/svelte/internal/index.mjs:679:25)
    at Object.useForm (/Users/sav/workspace/500/my-app/node_modules/svelte-use-form/src/useForm.ts:310:12)
    at /Users/sav/workspace/500/my-app/src/routes/index.svelte:6:22
    at Object.$$render (/Users/sav/workspace/500/my-app/node_modules/svelte/internal/index.mjs:1366:23)
    at Object.default (/Users/sav/workspace/500/my-app/src/node_modules/@sapper/internal/App.svelte:24:50)
    at /Users/sav/workspace/500/my-app/__sapper__/dev/server/server.js:419:66
    at Object.$$render (/Users/sav/workspace/500/my-app/node_modules/svelte/internal/index.mjs:1366:23)
    at /Users/sav/workspace/500/my-app/src/node_modules/@sapper/internal/App.svelte:20:18
    at $$render (/Users/sav/workspace/500/my-app/node_modules/svelte/internal/index.mjs:1366:23)
```

I don't think that the problem is Hint.svelte using typescript since it is only included in the ts folder to offer types but under the hood components/Hint.svelte is referenced. You can test this by deleting the ts folder. I would say that it's probably a sveltekit bug since it works in sapper and svelte.

I also tried a lot of stuff in sveltekit but there are still tons of bugs, I would recommend switching to sapper for the moment😅

**Comment by niklasgrewe** [comment]
Yes, you're right. If i removed the ts folder, nothing changed. Its a bug in sveltekit or vitejs, so this issue can be closed now 😅

**Comment by niklasgrewe** [comment]
i now use svelte and vitejs instead of sveltekit. Everything works, even HMR, but unfortunately I get the above error message again when I want to use `svelte-use-form`

```
Failed to init component
<Login>
Error: Function called outside component initialization
```
I can't explain why this error is generated. Apparently the error is not related to sveltekit after all.... Do you have an idea? 

Byw thank you very much for implementing the requested features, thats pretty cool - if I could use it 😄

**Comment by noahsalvi** [comment]
Do you maybe have a  repository that I can use to replicate your problem? and do other libraries work?

**Comment by niklasgrewe** [comment]
i created a small repo: https://github.com/niklasgrewe/svelte-use-form-500-error
i tested the library `svelte-hero-icons` and i don't get any errors on it

**Comment by noahsalvi** [comment]
Im still looking for a solution 🥲  but for now adding 
```
optimizeDeps: {
        exclude: ["svelte-use-form"],
    },
```
to your vite.config.js fixes it.

**Comment by Bandit** [comment]
I'm getting this on a fresh install of Sveltekit + Vite

**Comment by noahsalvi** [comment]
> I'm getting this on a fresh install of Sveltekit + Vite

Sorry for the late response...
I just tested it with @sveltejs/kit 1.0.0-next.131 and svelte-use-form 2.4.0 and it seems to work. Do you still have this problem or do you remember the versions with which you tested it?
